name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2
        
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install required applications
        run: sudo apt-get install pandoc wkhtmltopdf

      - name: Build
        run: ./make.sh

      - uses: actions/upload-artifact@v2
        name: Upload Artifact
        with:
          name: Flier.7z
          path: target/Flier.7z
